extends Node

enum TYPES {
	CHARACTER,
	WEAPON
}
# Different types of stats (eg.: Weapon's vs. Character's)


# LIST OF PRE-DEFINED STAT VALUES ---->

enum RELOAD_MODE {
	FULL,
	INDIVIDUAL,
	AUTO
}

enum WEAPON_TYPE {
	PROJECTILE,
	HITSCAN
}

enum EFFECT {
	NONE
}

# <----


enum STAT {
	ACCELERATION,
	MUZZLE_FLASH,
	UNLOCKED,
	DROPS_SHELL,
	MOVE_SPEED,
	HEALTH,
	ELEMENTAL_RESISTANCE,
	PICKUP_MAGNETIC,
	STRENGTH,
	SPEED,
	ACCURACY,
	ARMOR,
	WEIGHT,
	SPREAD,
	FIRE_CHARGE,
	MAGAZINE,
	FIRE_RATE,
	RELOAD_TIME,
	NOISE,
	RELOAD_MODE,
	AMMO,
	RECOIL,
	MULTISHOT,
	MULTISHOT_RANDOM,
	ARMOR_PIERCING,
	BURST,
	BURST_DELAY,
	AOE,
	EFFECT,
	EFFECT_DURATION,
	SPREADING_SCALING,
	HANDLING,
	PUNCH_THROUGH,
	WEAPON_TYPE,
	HOMING,
	FIRE_CHARGE_CONSUMES_AMMO,
	RANGE,
	KNOCKBACK,
	DAMAGE,
	BOUNCES,
	SHOOT_MODES
}
# List of all stat names (so you always get a autocomplete hints whenever
# calling/setting a stat; this way there are no typos nor inconsistencies anywhere!)

const STATS = {
	TYPES.CHARACTER: {
		STAT.ACCELERATION: 7.5,
		STAT.MOVE_SPEED: 300.0,
		STAT.HEALTH: 10.0,
		STAT.ELEMENTAL_RESISTANCE: 1.0,
		STAT.PICKUP_MAGNETIC: 300.0,
		
		STAT.STRENGTH: 1.0,
		STAT.SPEED: 1.0,
		STAT.ACCURACY: 1.0,
		STAT.ARMOR: 1.0,
		
		STAT.WEIGHT: 50.0
		},
		
	TYPES.WEAPON: {
		STAT.MUZZLE_FLASH: true,
		STAT.UNLOCKED: true,
		STAT.DROPS_SHELL: true,
		
		STAT.SPREAD: 3.5,
		STAT.FIRE_CHARGE: 0.0,
		STAT.MAGAZINE: 10.0,
		STAT.FIRE_RATE: 0.5,
		STAT.RELOAD_TIME: 1.25,
		STAT.NOISE: 550.0,
		STAT.RELOAD_MODE: 0,
		STAT.AMMO: -1.0,
		STAT.RECOIL: 1.0,
		STAT.MULTISHOT: 1.0,
		STAT.MULTISHOT_RANDOM: false,
		STAT.ARMOR_PIERCING: 1.0,
		STAT.BURST: 1.0,
		STAT.BURST_DELAY: 0.0,
		STAT.AOE: 0.0,
		STAT.EFFECT: 0,
		STAT.EFFECT_DURATION: 0.0,
		STAT.SPREADING_SCALING: 0.0,
		STAT.HANDLING: 1.0,
		STAT.PUNCH_THROUGH: 0,
		STAT.WEAPON_TYPE: 0,
		STAT.HOMING: 0.0,
		STAT.FIRE_CHARGE_CONSUMES_AMMO: true,
		STAT.RANGE: 200.0,
		STAT.KNOCKBACK: 3.5,
		STAT.MOVE_SPEED: 450.0,
		STAT.ACCELERATION: 0.0,
		STAT.DAMAGE: 3.0,
		STAT.BOUNCES: false,
		STAT.SHOOT_MODES: 1,
		STAT.WEIGHT: 10.0
		}
}
# Constant dictionary that properly attributes stats to each game object
